### ISSUE TITLE
v1 branch needs porting to latest  mdlayher / arp

### ISSUE THREAD

**Issue by mbanck** [cybertec-postgresql/vip-manager#128]
The 1.x branch fails to build on current Debian unstable, see also https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1026294:
```
github.com/cybertec-postgresql/vip-manager/ipmanager
# github.com/cybertec-postgresql/vip-manager/ipmanager
src/github.com/cybertec-postgresql/vip-manager/ipmanager/basicConfigurer_linux.go:101:3: cannot use c.VIP (variable of type net.IP) as type netip.Addr in argument to arp.NewPacket
src/github.com/cybertec-postgresql/vip-manager/ipmanager/basicConfigurer_linux.go:103:3: cannot use c.VIP (variable of type net.IP) as type netip.Addr in argument to arp.NewPacket
src/github.com/cybertec-postgresql/vip-manager/ipmanager/basicConfigurer_linux.go:125:3: cannot use c.VIP (variable of type net.IP) as type netip.Addr in argument to arp.NewPacket
src/github.com/cybertec-postgresql/vip-manager/ipmanager/basicConfigurer_linux.go:127:3: cannot use c.VIP (variable of type net.IP) as type netip.Addr in argument to arp.NewPacket
crypto/tls
[...]
dh_auto_build: error: cd obj-x86_64-linux-gnu && go install -trimpath -v -p 16 github.com/cybertec-postgresql/vip-manager github.com/cybertec-postgresql/vip-manager/checker github.com/cybertec-postgresql/vip-manager/ipmanager github.com/cybertec-postgresql/vip-manager/vipconfig returned exit code 2
make: *** [debian/rules:9: build] Error 25
```

This is due to this:
https://github.com/mdlayher/arp/commit/6706a2966875c189c24afd003ffe801ff69542a1

**Comment by mbanck** [comment]
It would be nice if this was fixed in a way so it worked for both versions of arp, so that vip-manager continues to build on older distributions

**Comment by pashagolub** [comment]
Hello, I cannot reproduce the bug:


```
$  go version
go version go1.19.3 linux/amd64

$ git status
On branch v1
Your branch is up to date with 'origin/v1'.

nothing to commit, working tree clean

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy

$ go build
go: downloading github.com/spf13/viper v1.10.1
go: downloading github.com/hashicorp/go-hclog v1.2.0
go: downloading github.com/hashicorp/serf v0.9.7
go: downloading github.com/mitchellh/mapstructure v1.4.3
go: downloading github.com/mdlayher/arp v0.0.0-20220221190821-c37aaafac7f9
go: downloading github.com/spf13/cast v1.4.1
go: downloading github.com/spf13/afero v1.8.2
go: downloading github.com/fsnotify/fsnotify v1.5.1
go: downloading github.com/subosito/gotenv v1.2.0
go: downloading gopkg.in/ini.v1 v1.66.4
go: downloading github.com/pelletier/go-toml v1.9.4
go: downloading golang.org/x/sys v0.0.0-20220330033206-e17cdc41300f
go: downloading github.com/mattn/go-isatty v0.0.14
go: downloading github.com/mattn/go-colorable v0.1.12
go: downloading golang.org/x/text v0.3.7
go: downloading github.com/mdlayher/packet v1.0.0
go: downloading github.com/armon/go-metrics v0.3.10
go: downloading golang.org/x/net v0.0.0-20220325170049-de3da57026de
go: downloading github.com/mdlayher/socket v0.2.3
go: downloading golang.org/x/sync v0.0.0-20210220032951-036812b2e83c

$ ls vip*
vip-manager

vipconfig:
config.go  vip-manager.yml

$ file vip-manager
vip-manager: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, Go BuildID=guTkkB97LklsNJPYHnFD/foXqCdqBfqOnHWec2Vds/1mB_6z77Ge22C-9k-Ocl/GzRglr5DoXbHNqBIztue, with debug_info, not stripped
```

**Comment by mbanck** [comment]
Well, I guess that's due to `github.com/mdlayher/arp v0.0.0-20220221190821-c37aaafac7f9` in `go.mod`. Debian doesn't have that luxury of just pinning something to a git commit, somebody uploaded a new version of `mdlayher/arp` and that is what we are stuck with. I've patched around that in the Debian packaging: https://salsa.debian.org/postgresql/vip-manager/-/blob/master/debian/patches/netip-port.patch

**Comment by pashagolub** [comment]
The `github.com/mdlayher/arp` doesn't have tags at all so the only possibility is to use git commit. I'm wondering why Debian behave like this... Anyway, thanks for your help!

**Comment by tpo** [comment]
> The `github.com/mdlayher/arp` doesn't have tags at all so the only possibility is to use git commit. I'm wondering why Debian behave like this... Anyway, thanks for your help!

Do you use Linux anywhere? It's nice to have a look at it, it works differently from Windows, there can be useful things to learn from it. More precisely to the point: People use and create Linux distributions to save work. Although Debian does not stand out with respect to sticking to released versions of software, there are some Linux distros that take a different approach. So sticking to releases of software is not a "Debian thing". OK, why would a distribution stick to released versions of libraries? Because if there's a problem (say a security problem, but also an integration problem, a configuration problem, a documentation problem etc.), then the question arises:

The piece of sofware X has this problem. We know softwares Y, Z, M, Q and B all depend on software X. Say the problem is fixed in X, do we now need to also take care of software Y, Z, M, Q and B (say, rebuild, re-link, recompile, redocument, reconfigure etc.)?

If Y, Z, M, Q and B use the same version of X, then the problem is vastly simplified. Maybe just uploading a new version of X will fix the problem for X, Z, M. Q and B without any further work.

However, if Y, Z, M, Q and B each use a different, therir own version for X then *each instance* will certainly need to be investigated separately:
* does the X problem occur in each of those versions that Y, Z, M, Q and B use?
* doe we have a patch for each version of X for Y, Z, M, Q and B?
* does upstream of the maintainer care about fixing (branching) each of the versions of X solely because some project Z is using some stale/pinned old version of X?
* if the maintainer or upstreap do not care, do we have someone with enough knowhow to fix that specific X version?
* if not then should we tell our users that their program Q that they are using daily is from this second on not supported any more and they are now exposed to a security vulnerability?
* if upgrading from some stale old/pinned version of X to a known fixed one, then can we tell if this will break projects M and Z? 
* etc. etc. etc. etc. you get some kind of combinatorial explosion aka DLL hell

Let me reverse the question: would you know if there was a security/stability/dataloss problem with github.com/mdlayher/arp? How would you know?

In distros you have a maintainer for software X. He the expert of software X and is responsible to take care of security/stability/dataloss problems in X. Once he fixes the problems in X they are fixed in *all the softwares Y, Z, M, Q, B etc. that depend on X, whithout those projects needing to do anything (as a rule of thumb).

**Comment by pashagolub** [comment]
> Do you use Linux anywhere?
Of course not! I'm a farmer boy and never saw a computer.

Anyway! This is an open source project. Patches are welcome!

**Comment by tpo** [comment]
> > Do you use Linux anywhere?
> 
> Of course not! I'm a farmer boy and never saw a computer.
> 
> Anyway! This is an open source project. Patches are welcome!

https://github.com/cybertec-postgresql/vip-manager/issues/128#issuecomment-1385727997 ?

**Comment by markwort** [comment]
I'm not sure if I'm missing something, but the issue is that debian sticks to an older version of the library (and also insists on packaging all dependencies required for packaging and not using any other dependency managers (like `go get`).

> It would be nice if this was fixed in a way so it worked for both versions of arp, so that vip-manager continues to build on older distributions

I agree, but we're not aware of any way to implement that. It's not that we can determine at runtime "we've been built using this lib version, we must execute these routines instead of those".
The code would need to be different before building. That is exactly how @mbanck has kindly patched it.

An alternative would be to fix that library to the last supported version in debian, but that is not good either.
What if the next distro comes along and decides that they only prepackage a different version?

There is no way to make everyone happy, which is why this is a downstream/packaging issue, I believe.

**Comment by mbanck** [comment]
No it's the other way round I think: vip-manager's (v1-branch)`go.mod` sticks to an older version of arp (v0.0.0-20220221190821-c37aaafac7f9) and Debian packaged a newer version (0.0~git20220512.6706a29-1) now (maybe some other Go package needed it or it is cleaner this way, it wasn't my call).

But yeah, it's likely not much we can do about I'm afraid. I'm currently experimenting with a pgdg branch for apt.postgresql.org which does the very evil thing of determining at build time what kind of dependencies are there and then applying (or reverting) patches accordingly, see https://salsa.debian.org/postgresql/vip-manager/-/commit/49a6e3ea9bcea66388ac1617bef0ff884622b1c7

**Comment by mbanck** [comment]
> The `github.com/mdlayher/arp` doesn't have tags at all so the only possibility is to use git commit. I'm wondering why Debian behave like this... Anyway, thanks for your help!

@pashagolub to clarify, Debian packages git commits as well, just a newer one as is required by vip-manager's v1 branch.

Also note that the v2/master branch has since moved forward an requires the same arp version as Debian has in testing/unstable now:

```
mba@curie:~/Projekte/OSS/vip-manager$ git checkout v1
Switched to branch 'v1'
Your branch is up to date with 'origin/v1'.
mba@curie:~/Projekte/OSS/vip-manager$ grep arp go.mod 
	github.com/mdlayher/arp v0.0.0-20220221190821-c37aaafac7f9
mba@curie:~/Projekte/OSS/vip-manager$ git checkout master
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
mba@curie:~/Projekte/OSS/vip-manager$ grep arp go.mod 
	github.com/mdlayher/arp v0.0.0-20220512170110-6706a2966875
```

**Comment by pashagolub** [comment]
Yeah, I know the latest `master` branch uses the newest version of `arp`. I just cannot get it why the old one needs the newest while it's said in `go.mod` to use the old one :)

**Comment by mbanck** [comment]
Debian does not download Go modules during build (that's against policy, not just for Go, but for other things like Python as well), it uses whatever it is packaged in the distribution, which is now the newer version of arp. So go.mod is only advisory for Debian package build.

**Comment by pashagolub** [comment]
I see now! Thanks a lot for clarifying @mbanck! 🤝
