### ISSUE TITLE
cluster ip confusion

### ISSUE THREAD

**Issue by prensgold** [cybertec-postgresql/vip-manager#147]
Hi ,

I installed the Postgresql ETCD Cluster on my local servers.
I installed your vip manager application to access databases over a single ip.
I was only able to see the cluster ip on one server.

In the screenshot below, the cluster ip output from the servers I set up in my own locale.

![image](https://user-images.githubusercontent.com/118886124/228716306-da1b9c94-19b2-4e04-adca-9acf6a565600.png)

When I wanted to set up and test the same architecture on amazon, I saw the cluster ip on all 3 servers.
and when I tried to connect to database with port 5000 from each server I was able to connect.

In the screenshot below, the cluster ip output from the servers I set up on amazon.

![image](https://user-images.githubusercontent.com/118886124/228716579-eb1c51a5-45d1-42fa-932e-08b906668dcb.png)

Cluster ip status confused me in two installations.
What is the correct output here? The operating systems are in the same version.
How can we interpret this situation?

Thanks

**Comment by prensgold** [comment]
Is it possible for you to give an opinion on this?

**Comment by tanganellilore** [comment]
I have similar issue when etcd is in the same machine where i deploy postgres (via vitabaks playbook).
In my case, the issue was related the multiple dcs assignement in `vip-manager` config.

In a situation with 3 node and 3 etcd in same node, if I `power-off` the node that have vip address, vip-manager go in a "stack" position and not update vip on new leader elected by patroni.
The only workaround, when you use etcd in the same machine of patroni/postgres, is to se it only one dcs (the localhost) and this will "resolve" the issue.

**Comment by markwort** [comment]
@prensgold 
>  I was only able to see the cluster ip on one server.

This is actually expected.
vip-manager will register the IP adress on the machine that matches the current leader in the patroni cluster, and it will deregister the address again when the machine is no longer the leader.

> When I wanted to set up and test the same architecture on amazon, I saw the cluster ip on all 3 servers.
> and when I tried to connect to database with port 5000 from each server I was able to connect.

Right now, vip-manager doesn't support AWS and I cannot understand how you managed to get that working as you describe it.
Maybe you created three independent patroni clusters instead of a single one with three members?
As far as I am aware, AWS doesn't support sending of gratuitous ARP messages (none of the public hosters do, as you could try to impersonate another server easily), so vip-manager would not work with AWS.
We currently support Hetzner API and there was a PoC for Hetzner cloud floating around, that could give you an idea on how to make vip-manager work with the AWS API to move around a virtual IP in AWS.

**Comment by markwort** [comment]
@tanganellilore
> In a situation with 3 node and 3 etcd in same node, if I power-off the node that have vip address, vip-manager go in a "stack" position and not update vip on new leader elected by patroni.

can you share some logs and your exact configuration?
You should only have one "dcs" section, but you can list multiple hosts in there.
I believe if you have multiple "dcs" sections, only the last one that you define is applied to the configuration.
You can verify this by looking at the configuration that etcd prints when starting up.

Having vip-manager only connect to etcd on localhost means you risk losing the VIP when you're stopping the etcd service on that node, but patroni keeps the leader running there.

**Comment by vitabaks** [comment]
> AWS doesn't support sending of gratuitous ARP messages (none of the public hosters do, as you could try to impersonate another server easily), so vip-manager would not work with AWS.

@markwort thanks for the comment
