### ISSUE TITLE
new raw package incompatible with golang < 1.12

### ISSUE THREAD

**Issue by tpo** [cybertec-postgresql/vip-manager#42]
Hi,

after merging the new arp code along with updated arp and raw packages, vip-manager no longer compiles under golang v1.11. It seems that code needs at least golang v1.12. See https://github.com/mdlayher/raw/issues/63

Current Debian stable (buster) has the golang v1.11 package , but there is golang v1.14 in buster-backports - see [here](https://packages.debian.org/search?keywords=golang). I'm not sure about the status of golang v1.14 in backports, but I'd *think* it's not supported on the same level as v1.11.

Similar for Ubuntu, where bionic has golang v1.10, later releases have golang >  v1.12 - see [here](https://packages.ubuntu.com/search?keywords=golang).

Please do not take my analysis above at face value, since I am not at home in Go development and so the above might not be 100% correct.

If my analysis above is correct however then please ponder whether you want to depend on Go > v1.12. If so, then I'd suggest to document that dependency explicitly in the README.

**Comment by tpo** [comment]
After installing golang 1.14 from buster-backports the code compiles just fine, so I am confirming, vip-manager with the updated arp code depends on golang > 1.11.

**Comment by markwort** [comment]
dear @tpo thanks for noticing this.
I think I had to switch to a newer version of golang quite some time ago, exactly due to that f.SyscallConn undefined error in the github.com/mdlayer/arp library.

I think it is not reasonable for us to stick to such an old version. Especially since I think it is unlikely that debian/ubuntu in their current versions will be shipping the next release of vip-manager.
And regardless, since the app is compiled into machine code, it can be very easily built in a container with a modern golang version and then be installed in a different system...

you're right - we should document this.
Looking at the Dockerfile (which can be used to build the binary without installing a (new) version of golang on your own system), it seems we should replace the base container, as it is using the golang:alpine image. Alpine is problematic since it uses musl libc, not glibc...
