### ISSUE TITLE
Do nothing when vip-manager is gracefully shutdown

### ISSUE THREAD

**Issue by Faffnir** [cybertec-postgresql/vip-manager#7]
Currently the vip-manager unassigns itself the virtual ip if the vip-manager is gracefully shutdown.

In my opinion the vip-manager should do nothing when shutdown in order to do a clean upgrade of the vip-manager or for basic maintenance?

What do you think @ants ?

**Comment by ants** [comment]
I think we probably want two shutdown modes. Having the IP still assigned
when somebody else takes the leader key is going to cause all kinds of fun.
That's why I defaulted to the safe option of just releasing the IP.
However, for maintenance it would be good to have the option to shut down
without releasing. There actually is that option right now via SIGKILL, but
that is not a good practice. Maybe let's have SIGINT have  a release
semantic and make SIGTERM do an immediate shut down.

On Nov 1, 2017 6:32 PM, "Faffnir" <notifications@github.com> wrote:

Currently the vip-manager unassigns itself the virtual ip if the
vip-manager is gracefully shutdown.

In my opinion the vip-manager should do nothing when shutdown in order to
do a clean upgrade of the vip-manager or for basic maintenance?

What do you think @ants <https://github.com/ants> ?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/cybertec-postgresql/vip-manager/issues/7>, or mute the
thread

**Comment by Faffnir** [comment]
Isn't that two seperate things?
When somebody else takes over the vip this is called:
https://github.com/cybertec-postgresql/vip-manager/blob/ecdf8ea734f5ce253840ee1911ef2eb95c9366db/ip_manager.go#L69
But when the process receives a not necessarily vip-change-based interrupt externally calls this:
https://github.com/cybertec-postgresql/vip-manager/blob/ecdf8ea734f5ce253840ee1911ef2eb95c9366db/ip_manager.go#L80

I totally agree with you that the first one has to stay the same but I would just get rid of the second one.
It is most likely that if an external interrupt is issued, it originates from the operating system or a user interaction.
If that interrupt occured due to a vip-change it shouldn't be a problem to stay with the same IP either because with the gratuitous arp the former vip-owner is ignored anyways?

I see a bigger problem with unassigning the ip-address as it could lead to a situations where no servers have the vip.

**Comment by ants** [comment]
If two hosts have the same vip then it isn't a case of "latest one wins", new hosts will send arp queries and old hosts will have their arp cache entry age out if the connection isn't used for 60 seconds. The two hosts with same vip will then race to respond to the request, and it's much less clear who will win that race. That's why I'm much more worried about two servers having the same vip.

Looking at the code, it looks like we don't catch SIGTERM right now anyway. So it actually already works like I proposed.

If you shutdown vip-manager with `kill -SIGINT $pid`, it will release the vip, if you shutdown with `kill -SIGTERM $pid`, the vip is not released. The only nasty part is that on startup we deconfigure the IP and then immediately reconfigure it once first response from etcd comes back.

I think we should try to get the initial state from cluster consensus and initialize `IPManager.current_state` with that value. If getting the initial state times out (a new timeout parameter, defaulting to 30s), just start up IPManager with initial state false.

**Comment by ants** [comment]
The new timeout should also apply for the recheck loop in leader checker:

https://github.com/cybertec-postgresql/vip-manager/blob/master/checker/etcd_leader_checker.go#L47-L54

If we don't get a response within the specified time, we issue a false state.

**Comment by Faffnir** [comment]
Mh... That's something we should test with another setup. In our cluster setup the "latest one wins". If the vip is unassigned during the 60 seconds cache entry duration, it will actually fallback to this server... That's what we actually tested in our infrastructure but I absolutely agree what you said if you only focus on the arp-documentation.
Could it be possible that our switch is handling this and that would mean the behaviour actually differs between different switch-server-cluster setup?

So coming back to the actual problem with vip deconfiguring.
Should we handle the deconfigure/configure problem when starting vip-manager?
Should we add the SIGTERM handling or should we just not handle it because it already handles it like we want it to? ( would be more explicit to someone else who is reading the code if we add it?)

**Comment by ants** [comment]
My understanding of the ARP protocol is that first response wins. So when a client needs to know which host is serving the IP it will send out a broadcast request, if the network path to one host is shorter that one will get to respond first and it's response will arrive earlier. Unless there is a delay from network congestion or the packet is dropped. So for a given setup some clients will see server A almost always win, some will see server B almost always win, and in a very unlikely case of equal network delay a client could see randomly A or B.

I think for SIGTERM it would be enough to just document this behavior. A prerequisite for that would be that we actually have documentation, which seems like a nice idea. I'll try to get to writing some within the next couple of days, unless you want to volunteer.

**Comment by ants** [comment]
Would be interesting to see tcpdump of the ARP traffic from all servers to see what is going on. I will try it out once I get my hands back on our hardware based test setup.

I'll try to write down first cut of the docs tomorrow. If you have the time you are welcome to tackle the startup issue, looking at my schedule I don't think I will get enough time to implement it in the next 2 weeks.

**Comment by Faffnir** [comment]
I actually catched all the traffic with tcpdump but maybe it is also possible to have a live-update of the arp-table of the switch...
If something really interesting happens we will most likely write a blog-post to also publish the test-results.
I will tackle the startup issue as soon as i can!
